# Generated by Django 5.0.6 on 2024-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('email', models.CharField(max_length=250)),
                ('mobile', models.IntegerField()),
                ('skills', models.CharField(max_length=250)),
                ('workexperince', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=250)),
                ('certifications', models.CharField(max_length=250)),
                ('projecttitle', models.CharField(max_length=250)),
                ('projectdescription', models.TextField()),
                ('projectlink', models.CharField(max_length=250)),
            ],
        ),
    ]
