# Generated by Django 5.0.6 on 2024-07-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
